version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - microservice-network

  auth-app:
    build: ./AuthApplication
    container_name: auth-container
    ports:
      - "8082:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice-network

  product-app:
    build: ./ProductApplication
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservice-network

  order-app:
    build: ./OrderService
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservice-network

networks:
  microservice-network: